Remove charge_id constraints on refunds and refunds_history tables
For some reason upgrading to liquibase 4.2.x results in the following error:

```
liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set migrations.xml::drop not null constraint on charge_id on refunds table:::
     Reason: liquibase.exception.DatabaseException: ERROR: column "charge_id" of relation "refunds" is an identity column [Failed SQL: (0) ALTER TABLE public.refunds ALTER COLUMN  charge_id DROP NOT NULL]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:124)
```

I'm not sure why this is problematic as the foreign key constraint was already
dropped.

However it seems we can remove the lines removed in this commit as the
charge_id has been dropped from the refunds and refunds_history table anyway.